### ISSUE TITLE
下载docx文件报错,docx文件无法打开

### ISSUE THREAD

**Issue by woshidafengzi** [inceptiongt/Yapi-plugin-export-docx-data#2]
error: Error: Can't find end of central directory : is this a zip file ? If it is, see http://stuk.github.io/jszip/documentation/howto/read_zip.html
    at ZipEntries.readEndOfCentral (/my-yapi/vendors/node_modules/jszip/lib/zipEntries.js:173:23)
    at ZipEntries.load (/my-yapi/vendors/node_modules/jszip/lib/zipEntries.js:274:14)
    at new ZipEntries (/my-yapi/vendors/node_modules/jszip/lib/zipEntries.js:22:14)
    at JSZip.module.exports [as load] (/my-yapi/vendors/node_modules/jszip/lib/load.js:19:18)
    at new JSZip (/my-yapi/vendors/node_modules/jszip/lib/index.js:39:14)
    at toDocx (/my-yapi/vendors/node_modules/yapi-plugin-export-docx-data/json2docx.js:17:15)
    at exportController.exportData (/my-yapi/vendors/node_modules/yapi-plugin-export-docx-data/controller.js:90:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)

**Comment by benjamin555** [comment]
Error: Can't find end of central directory : is this a zip file 我也是遇到这个问题了 。1.8.3版本。有处理的吗？

**Comment by benjamin555** [comment]
可以了 模版文件的内容不对。应该是这个
https://github.com/inceptiongt/Yapi-plugin-export-docx-data/blob/master/input.docx

**Comment by xjzyy** [comment]
> 可以出模版文件的内容不对。应该是这个 https://github.com/inceptiongt/Yapi-plugin-export-docx-data/blob/master/input.docx

非常感谢，官方的一直报错，你的模板解决了我的问题。
